


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."condition" AS ENUM (
    '1',
    '2',
    '3'
);


ALTER TYPE "public"."condition" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."add_owner_on_club_create"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into "Role" ("UID", club_id, role)
  values (auth.uid(), new.club_id, 'Owner');

  return new;
end;
$$;


ALTER FUNCTION "public"."add_owner_on_club_create"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_auth_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public."User" ("UID")
  VALUES (NEW.id);

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_auth_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Club" (
    "club_id" numeric NOT NULL,
    "name" character varying
);


ALTER TABLE "public"."Club" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Role" (
    "role" character varying,
    "club_id" numeric NOT NULL,
    "UID" "uuid"
);


ALTER TABLE "public"."Role" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."User" (
    "email" character varying,
    "fname" character varying,
    "lname" character varying,
    "password" character varying,
    "user_image_url" "text",
    "UID" "uuid" NOT NULL
);


ALTER TABLE "public"."User" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."item" (
    "item_id" bigint NOT NULL,
    "name" character varying,
    "condition" "public"."condition",
    "description" "text",
    "cat_id" numeric,
    "item_image_url" "text"
);


ALTER TABLE "public"."item" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."item_category" (
    "item_cat_id" numeric NOT NULL,
    "name" character varying NOT NULL,
    "quantity" character varying NOT NULL,
    "description" "text",
    "club_id" numeric NOT NULL,
    "item_cat_image_url" "text"
);


ALTER TABLE "public"."item_category" OWNER TO "postgres";


ALTER TABLE "public"."item" ALTER COLUMN "item_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Club"
    ADD CONSTRAINT "Club_pkey" PRIMARY KEY ("club_id");



ALTER TABLE ONLY "public"."Role"
    ADD CONSTRAINT "Role_club_id_key" UNIQUE ("club_id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("UID");



ALTER TABLE ONLY "public"."item_category"
    ADD CONSTRAINT "item_category_pkey" PRIMARY KEY ("item_cat_id");



ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_pkey" PRIMARY KEY ("item_id");



CREATE OR REPLACE TRIGGER "on_club_created" AFTER INSERT ON "public"."Club" FOR EACH ROW EXECUTE FUNCTION "public"."add_owner_on_club_create"();



ALTER TABLE ONLY "public"."Role"
    ADD CONSTRAINT "Role_UID_fkey" FOREIGN KEY ("UID") REFERENCES "public"."User"("UID") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Role"
    ADD CONSTRAINT "Role_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."Club"("club_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_cat_id_fkey" FOREIGN KEY ("cat_id") REFERENCES "public"."item_category"("item_cat_id");



ALTER TABLE ONLY "public"."item_category"
    ADD CONSTRAINT "item_category_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."Club"("club_id");



CREATE POLICY "Admin and Owner Can Update Their Clubs" ON "public"."Club" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."Role"
  WHERE (("Role"."UID" = "auth"."uid"()) AND ("Role"."club_id" = "Club"."club_id") AND ((("Role"."role")::"text" = 'Admin'::"text") OR (("Role"."role")::"text" = 'Owner'::"text"))))));



CREATE POLICY "Admin or owner can do all" ON "public"."item" USING ((EXISTS ( SELECT 1
   FROM ("public"."item_category" "ic"
     JOIN "public"."Role" "r" ON (("r"."club_id" = "ic"."club_id")))
  WHERE (("ic"."item_cat_id" = "item"."cat_id") AND ("r"."UID" = "auth"."uid"()) AND ((("r"."role")::"text" = 'Admin'::"text") OR (("r"."role")::"text" = 'Owner'::"text"))))));



CREATE POLICY "Admin or owner can do all" ON "public"."item_category" USING ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "item_category"."club_id") AND ((("r"."role")::"text" = 'Admin'::"text") OR (("r"."role")::"text" = 'Owner'::"text"))))));



CREATE POLICY "Admins Can Change Club Roles" ON "public"."Role" AS RESTRICTIVE FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Admin'::"text") AND (("Role"."role")::"text" <> 'Admin'::"text") AND (("Role"."role")::"text" <> 'Owner'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Admin'::"text")))));



CREATE POLICY "Admins can insert roles" ON "public"."Role" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Admin'::"text") AND (("Role"."role")::"text" <> 'Owner'::"text")))));



CREATE POLICY "Allow Public Read" ON "public"."Role" FOR SELECT USING (true);



CREATE POLICY "Allow Public Read" ON "public"."item" FOR SELECT USING (true);



CREATE POLICY "Allow public read" ON "public"."Club" FOR SELECT USING (true);



CREATE POLICY "Allow public read" ON "public"."item_category" FOR SELECT USING (true);



ALTER TABLE "public"."Club" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Owner Can Change Roles" ON "public"."Role" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Admin'::"text") AND (("Role"."role")::"text" <> 'Owner'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Owner'::"text")))));



CREATE POLICY "Owners can insert roles" ON "public"."Role" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."Role" "r"
  WHERE (("r"."UID" = "auth"."uid"()) AND ("r"."club_id" = "Role"."club_id") AND (("r"."role")::"text" = 'Owner'::"text") AND (("Role"."role")::"text" <> 'Owner'::"text")))));



ALTER TABLE "public"."Role" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "User can edit own row" ON "public"."User" FOR UPDATE USING (("auth"."uid"() = "UID")) WITH CHECK (("auth"."uid"() = "UID"));



CREATE POLICY "User can select own row" ON "public"."User" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "UID"));



CREATE POLICY "any authenticated user can create a club" ON "public"."Club" FOR INSERT TO "authenticated" WITH CHECK (true);



ALTER TABLE "public"."item" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."item_category" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."add_owner_on_club_create"() TO "anon";
GRANT ALL ON FUNCTION "public"."add_owner_on_club_create"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."add_owner_on_club_create"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_auth_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_auth_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_auth_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."Club" TO "anon";
GRANT ALL ON TABLE "public"."Club" TO "authenticated";
GRANT ALL ON TABLE "public"."Club" TO "service_role";



GRANT ALL ON TABLE "public"."Role" TO "anon";
GRANT ALL ON TABLE "public"."Role" TO "authenticated";
GRANT ALL ON TABLE "public"."Role" TO "service_role";



GRANT ALL ON TABLE "public"."User" TO "anon";
GRANT ALL ON TABLE "public"."User" TO "authenticated";
GRANT ALL ON TABLE "public"."User" TO "service_role";



GRANT ALL ON TABLE "public"."item" TO "anon";
GRANT ALL ON TABLE "public"."item" TO "authenticated";
GRANT ALL ON TABLE "public"."item" TO "service_role";



GRANT ALL ON TABLE "public"."item_category" TO "anon";
GRANT ALL ON TABLE "public"."item_category" TO "authenticated";
GRANT ALL ON TABLE "public"."item_category" TO "service_role";



GRANT ALL ON SEQUENCE "public"."item_item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."item_item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."item_item_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();


